name = "chickenroadbonus-net-pk"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=chickenroadbonus.net.pk"
HMAC_KEY = "c503a453dae4f13b93faad11b35cbca2a2f16df6b712f64af71231dd47fbfaf2"
COOKIE_NAME = "jr4"
PLAY_PATH = "start-now"
BUTTON_ID = "pd19e163e8c25914bbf470178926ec987"
GATE_SALT = "b8b991d80906a04f"
